import React from 'react'
import Card from '../main/Card'
import { Col } from 'react-bootstrap'
import Row from 'react-bootstrap/Row'
import Container from 'react-bootstrap/Container'
function CardList() {
  return (
    <>
      <Container>
        <Row>
          <Col xs={6} md={4} className="card-style">
            <Card
              title={'新北耶誕'}
              text={`刻年在一真升友在，夜長能前路大她力去主保：頭的母打字會，然算子在待的際和體`}
              location={'中壢市'}
              image={'testImage.jpg'}
              time1={'2020/12/24'}
              time2={-1}
              duration={3}
              price={-1}
              person={'王大明'}
              like={222}
              mark={222}
            />
          </Col>
          <Col xs={6} md={4}>
            <Card
              title={'新北耶誕'}
              text={`刻年在一真升友在，夜長能前路大她力去主保：頭的母打字會，然算子在待的際和體`}
              location={'中壢市'}
              image={'testImage.jpg'}
              time1={'2020/12/24'}
              time2={-1}
              duration={3}
              price={-1}
              person={'王大明'}
              like={222}
              mark={222}
            />
          </Col>
          <Col xs={6} md={4}>
            <Card
              title={'新北耶誕'}
              text={`刻年在一真升友在，夜長能前路大她力去主保：頭的母打字會，然算子在待的際和體`}
              location={'中壢市'}
              image={'testImage.jpg'}
              time1={'2020/12/24'}
              time2={-1}
              duration={3}
              price={-1}
              person={'王大明'}
              like={222}
              mark={222}
            />
          </Col>
          <Col xs={6} md={4}>
            <Card
              title={'新北耶誕'}
              text={`刻年在一真升友在，夜長能前路大她力去主保：頭的母打字會，然算子在待的際和體`}
              location={'中壢市'}
              image={'testImage.jpg'}
              time1={'2020/12/24'}
              time2={-1}
              duration={3}
              price={-1}
              person={'王大明'}
              like={222}
              mark={222}
            />
          </Col>
          <Col xs={6} md={4}>
            <Card
              title={'新北耶誕'}
              text={`刻年在一真升友在，夜長能前路大她力去主保：頭的母打字會，然算子在待的際和體`}
              location={'中壢市'}
              image={'testImage.jpg'}
              time1={'2020/12/24'}
              time2={-1}
              duration={3}
              price={-1}
              person={'王大明'}
              like={222}
              mark={222}
            />
          </Col>
          <Col xs={6} md={4}>
            <Card
              title={'新北耶誕'}
              text={`刻年在一真升友在，夜長能前路大她力去主保：頭的母打字會，然算子在待的際和體`}
              location={'中壢市'}
              image={'testImage.jpg'}
              time1={'2020/12/24'}
              time2={-1}
              duration={3}
              price={-1}
              person={'王大明'}
              like={222}
              mark={222}
            />
          </Col>
          <Col xs={6} md={4}>
            <Card
              title={'新北耶誕'}
              text={`刻年在一真升友在，夜長能前路大她力去主保：頭的母打字會，然算子在待的際和體`}
              location={'中壢市'}
              image={'testImage.jpg'}
              time1={'2020/12/24'}
              time2={-1}
              duration={3}
              price={-1}
              person={'王大明'}
              like={222}
              mark={222}
            />
          </Col>
          <Col xs={6} md={4}>
            <Card
              title={'新北耶誕'}
              text={`刻年在一真升友在，夜長能前路大她力去主保：頭的母打字會，然算子在待的際和體`}
              location={'中壢市'}
              image={'testImage.jpg'}
              time1={'2020/12/24'}
              time2={-1}
              duration={3}
              price={-1}
              person={'王大明'}
              like={222}
              mark={222}
            />
          </Col>
          <Col xs={6} md={4}>
            <Card
              title={'新北耶誕'}
              text={`刻年在一真升友在，夜長能前路大她力去主保：頭的母打字會，然算子在待的際和體`}
              location={'中壢市'}
              image={'testImage.jpg'}
              time1={'2020/12/24'}
              time2={-1}
              duration={3}
              price={-1}
              person={'王大明'}
              like={222}
              mark={222}
            />
          </Col>
          <Col xs={6} md={4}>
            <Card
              title={'新北耶誕'}
              text={`刻年在一真升友在，夜長能前路大她力去主保：頭的母打字會，然算子在待的際和體`}
              location={'中壢市'}
              image={'testImage.jpg'}
              time1={'2020/12/24'}
              time2={-1}
              duration={3}
              price={-1}
              person={'王大明'}
              like={222}
              mark={222}
            />
          </Col>
          <Col xs={6} md={4}>
            <Card
              title={'新北耶誕'}
              text={`刻年在一真升友在，夜長能前路大她力去主保：頭的母打字會，然算子在待的際和體`}
              location={'中壢市'}
              image={'testImage.jpg'}
              time1={'2020/12/24'}
              time2={-1}
              duration={3}
              price={-1}
              person={'王大明'}
              like={222}
              mark={222}
            />
          </Col>
          <Col xs={6} md={4}>
            <Card
              title={'新北耶誕'}
              text={`刻年在一真升友在，夜長能前路大她力去主保：頭的母打字會，然算子在待的際和體`}
              location={'中壢市'}
              image={'testImage.jpg'}
              time1={'2020/12/24'}
              time2={-1}
              duration={3}
              price={-1}
              person={'王大明'}
              like={222}
              mark={222}
            />
          </Col>
          <Col xs={6} md={4}>
            <Card
              title={'新北耶誕'}
              text={`刻年在一真升友在，夜長能前路大她力去主保：頭的母打字會，然算子在待的際和體`}
              location={'中壢市'}
              image={'testImage.jpg'}
              time1={'2020/12/24'}
              time2={-1}
              duration={3}
              price={-1}
              person={'王大明'}
              like={222}
              mark={222}
            />
          </Col>
          <Col xs={6} md={4}>
            <Card
              title={'新北耶誕'}
              text={`刻年在一真升友在，夜長能前路大她力去主保：頭的母打字會，然算子在待的際和體`}
              location={'中壢市'}
              image={'testImage.jpg'}
              time1={'2020/12/24'}
              time2={-1}
              duration={3}
              price={-1}
              person={'王大明'}
              like={222}
              mark={222}
            />
          </Col>
          <Col xs={6} md={4}>
            <Card
              title={'新北耶誕'}
              text={`刻年在一真升友在，夜長能前路大她力去主保：頭的母打字會，然算子在待的際和體`}
              location={'中壢市'}
              image={'testImage.jpg'}
              time1={'2020/12/24'}
              time2={-1}
              duration={3}
              price={-1}
              person={'王大明'}
              like={222}
              mark={222}
            />
          </Col>
        </Row>
      </Container>
    </>
  )
}
export default CardList
