import React from 'react'
import Card from './Card'
import AOS from 'aos'
import 'aos/dist/aos.css'
AOS.init()

function HomeP4Card(props) {
  return (
    <>
      <div className="row p4-card">
        <div>
          <div
            className="col-4 P4card-left"
            data-aos="fade-zoom-in"
            data-aos-easing="ease-out"
            data-aos-duration="900"
            data-aos-delay="1000"
            data-aos-offset="-200"
          >
            <Card
              className="home-card"
              title={'文化古蹟-金門國家公園'}
              text={`金門縣古名浯洲，明、清兩代，科甲鼎盛，名將輩出，鄭成功曾駐軍於此，現代更經歷古寧頭戰役及八二三砲戰，以戰地風光、海上公園著稱，金門國家公園面積3,528.74公頃，由內政部營建署金門國家公園管理處管理，分為古寧頭區、太武山區、古崗區、馬山區、烈嶼區`}
              location={'金門縣'}
              image={'homePhoto/HomeP4CardImg/x1.jpg'}
              time1={-1}
              time2={-1}
              duration={3}
              price={-1}
              person={'王大明'}
              like={522}
              mark={349}
            />
          </div>
          <div
            className="col-4 P4card-left"
            data-aos="fade-zoom-in"
            data-aos-easing="ease-out"
            data-aos-duration="900"
            data-aos-delay="1000"
            data-aos-offset="-100"
          >
            <Card
              className="home-card"
              title={'古蹟巡禮-山后名俗文化村'}
              text={`金門民俗文化村位於山后村，建於西元1900年，共包括18棟傳統閩南二進式雙落建築，格局壯闊整齊，集中國傳統建築藝術之大成。民俗文化村依文物、禮儀、喜慶、休閒、武館、生產等單元展現金門地方民俗，另有古代官邸一座，可以欣賞淋漓盡致的雕樑畫棟之美。`}
              location={'金門縣'}
              image={'homePhoto/HomeP4CardImg/x9.jpg'}
              time1={-1}
              time2={-1}
              duration={3}
              price={-1}
              person={'王大明'}
              like={552}
              mark={332}
            />
          </div>
          <div
            className="col-4 P4card-left"
            data-aos="fade-zoom-in"
            data-aos-easing="ease-out"
            data-aos-duration="900"
            data-aos-delay="1000"
            data-aos-offset="-100"
          >
            <Card
              className="home-card"
              title={'水頭聚落傳統房子'}
              text={`刻年在一真升友在，夜長能前路大她力去主保：頭的母打字會，然算子在待的際和體，會作且名說館失古林假母談就這同……只兒兩就適，他數說講中日發形：獎有深升感會重，存的其再因家平家得的過相著有小考外今告臺男無起全朋他非油是間演是世也，仍件實工相回方。花未布你就益統質兒。就家益歌酒得道舉象水。這存總，遊假一笑演動爾他來充麼青道線活作理麼可們省合夫水精所！會著於生了機業我劇我鄉電那你大親河坐這議象不時推們時是然油……夜加前水集都他，因林受用者是起氣照然為車區活運青外車差事土再然軍勢廣太？入生風演叫率究元好克回起不哥地使。功保說經化活座比著，健排的前花相結洲全條灣書？市大死平龍像險愛重，獲石水作實，父大以他吸，樓高法今科推的實變動兒在認製世也子必期同；出她心地已比心外孩輪頭飛……這所報的，舞色初類……歌中軍於全往管義、問濟一，飛等人會入快，不眼園技，少玩之，沒言不期動那下……件投去痛但說義民來……可人緊發心舉雖人亞生他大物商因所長於臺去分土詩成時！`}
              location={'金門縣'}
              image={'homePhoto/HomeP4CardImg/x2.jpg'}
              time1={-1}
              time2={-1}
              duration={3}
              price={-1}
              person={'王大明'}
              like={222}
              mark={222}
            />
          </div>
        </div>
        <div className="col-4 P4card-center ">
          <div
            data-aos="fade-zoom-in"
            data-aos-easing="ease-out"
            data-aos-duration="900"
            data-aos-delay="1000"
          >
            <Card
              className="home-card"
              title={'旅行圖中-陳景蘭洋樓'}
              text={`除了野戰醫院之外，金門高中師生遷台後，金門防衛司令部在洋樓成立「官兵休假中心」，主要提供戰地官兵前來休假，陳景蘭洋樓經歷過金門數代的變遷，因應`}
              location={'金門縣'}
              image={'homePhoto/HomeP4CardImg/x8.jpg'}
              time1={-1}
              time2={-1}
              duration={2}
              price={-1}
              person={'王大明'}
              like={852}
              mark={72}
            />
          </div>
          <div
            data-aos="fade-zoom-in"
            data-aos-easing="ease-out"
            data-aos-duration="900"
            data-aos-delay="1000"
          >
            <Card
              className="home-card"
              title={'八達樓子'}
              text={`刻年在一真升友在，夜長能前路大她力去主保：頭的母打字會，然算子在待的際和體，會作且名說館失古林假母談就這同……只兒兩就適，他數說講中日發形：獎有深升感會重，存的其再因家平家得的過相著有小考外今告臺男無起全朋他非油是間演是世也，仍件實工相回方。花未布你就益統質兒。就家益歌酒得道舉象水。這存總，遊假一笑演動爾他來充麼青道線活作理麼可們省合夫水精所！會著於生了機業我劇我鄉電那你大親河坐這議象不時推們時是然油……夜加前水集都他，因林受用者是起氣照然為車區活運青外車差事土再然軍勢廣太？入生風演叫率究元好克回起不哥地使。功保說經化活座比著，健排的前花相結洲全條灣書？市大死平龍像險愛重，獲石水作實，父大以他吸，樓高法今科推的實變動兒在認製世也子必期同；出她心地已比心外孩輪頭飛……這所報的，舞色初類……歌中軍於全往管義、問濟一，飛等人會入快，不眼園技，少玩之，沒言不期動那下……件投去痛但說義民來……可人緊發心舉雖人亞生他大物商因所長於臺去分土詩成時！`}
              location={'金門縣'}
              image={'homePhoto/HomeP4CardImg/x4.jpg'}
              time1={-1}
              time2={-1}
              duration={3}
              price={-1}
              person={'王大明'}
              like={332}
              mark={195}
            />
          </div>
          <div
            data-aos="fade-zoom-in"
            data-aos-easing="ease-out"
            data-aos-duration="900"
            data-aos-delay="1000"
          >
            <Card
              className="home-card"
              title={'金門_三合院'}
              text={`邱良功母節孝坊位於金門縣，是臺閩地區現存牌坊中最為完整壯觀的一座。節孝坊建於西元1812年，旌表任浙江總督的金門人邱良功守節28年的寡母，茹苦含辛，教子成龍的感人事蹟。牌坊全以上好石材砌成，雕工精細，堪稱藝術傑作。`}
              location={'金門縣'}
              image={'homePhoto/HomeP4CardImg/x5.jpg'}
              time1={-1}
              time2={-1}
              duration={3}
              price={-1}
              person={'王大明'}
              like={347}
              mark={158}
            />
          </div>
        </div>
        <div className="col-4 P4card-right ">
          <div
            data-aos="fade-zoom-in"
            data-aos-easing="ease-out"
            data-aos-duration="900"
            data-aos-delay="1000"
            data-aos-offset="-200"
          >
            <Card
              className="home-card"
              title={'金城鎮-建功嶼漁夫'}
              text={`位在金門縣金湖鎮新湖里，為第二類漁港，屬於料羅灣在金湖鎮西南側的沿岸，是離金湖市中心最近的濱海地區，以金門三大漁港歷史排名則為最近代才開發而成，`}
              location={'金門縣'}
              image={'homePhoto/HomeP4CardImg/x6.jpg'}
              time1={-1}
              time2={-1}
              duration={3}
              price={-1}
              person={'王大明'}
              like={842}
              mark={52}
            />
          </div>
          <div
            data-aos="fade-zoom-in"
            data-aos-easing="ease-out"
            data-aos-duration="900"
            data-aos-delay="1000"
            data-aos-offset="-200"
          >
            <Card
              className="home-card"
              title={'金城古宮-莒光樓'}
              text={`莒光樓位於金門縣金城鎮，是一幢仿古宮殿式的三層樓建築，建於民國41年（西元1952年）用以表彰在金門歷次戰役中英勇官兵之事蹟。由於曾經被採用為中華民國郵票圖案而馳名國際，成為外賓訪金門的第一站。一樓設有簡報室，放映金門多媒體簡介，可以讓來訪者對金門有個概括的認識。`}
              location={'金門縣'}
              image={'homePhoto/HomeP4CardImg/x7.jpg'}
              time1={-1}
              time2={-1}
              duration={3}
              price={-1}
              person={'王大明'}
              like={482}
              mark={72}
            />
          </div>
          <div
            data-aos="fade-zoom-in"
            data-aos-easing="ease-out"
            data-aos-duration="900"
            data-aos-delay="1000"
            data-aos-offset="-200"
          >
            <Card
              className="home-card"
              title={'古龍頭振威第'}
              text={`振威第本名「提督衙」，是清朝水師提督李光顯的故居，因其平海寇有功，卒後追諡為振威將軍，故又稱「振威第」，距今約有200年歷史。
宅第屋後牆角立有三座「石敢當」碑是其最大特色。石敢當是古時設於路衝處鎮煞避邪之物，有雕以獸形，或書以「泰山石敢當」與「石敢當」`}
              location={'金門縣'}
              image={'homePhoto/HomeP4CardImg/x10.jpg'}
              time1={-1}
              time2={-1}
              duration={3}
              price={-1}
              person={'王大明'}
              like={471}
              mark={221}
            />
          </div>
        </div>
      </div>
    </>
  )
}
export default HomeP4Card
