import React from 'react'
import Card from './Card'

function HomeP5Card(props) {
  return (
    <>
      <div className="row p4-card">
        <div className="col-4 P5card-left">
          <div
            data-aos="fade-zoom-in"
            data-aos-easing="ease-out"
            data-aos-duration="900"
            data-aos-delay="1000"
            data-aos-offset="-200"
          >
            <Card
              className="home-card"
              title={'阿里山-日出之旅'}
              text={`嘉義阿里山除了搭小火車、賞日出、看神木這些經典玩法之外，其實還有不少非常有趣的阿里山旅遊景點，可以在大自然的懷抱中，漫步在山林`}
              location={'嘉義縣'}
              image={'homePhoto/HomeP5CardImg/s1.jpg'}
              time1={-1}
              time2={-1}
              duration={2}
              price={-1}
              person={'王大明'}
              like={672}
              mark={95}
            />
          </div>
          <div
            data-aos="fade-zoom-in"
            data-aos-easing="ease-out"
            data-aos-duration="900"
            data-aos-delay="1000"
            data-aos-offset="-200"
          >
            <Card
              className="home-card"
              title={'奮起湖一日遊'}
              text={`日出、鐵道，變幻莫測的流雲、飛瀑，還有層次分明的茶園風光及原鄉人文采風，阿里山的美好就等你來體驗！ 定位點. All 全部景點 · 戶外踏青 · 生態自然 · 休閒`}
              location={'嘉義縣'}
              image={'homePhoto/HomeP5CardImg/s2.jpg'}
              time1={-1}
              time2={-1}
              duration={3}
              price={-1}
              person={'王大明'}
              like={411}
              mark={361}
            />
          </div>
          <div
            data-aos="fade-zoom-in"
            data-aos-easing="ease-out"
            data-aos-duration="900"
            data-aos-delay="1000"
            data-aos-offset="-200"
          >
            <Card
              className="home-card"
              title={'參訪百年砌石梯田'}
              text={`除了許多人熟知的奮起湖、眠月線、小火車以外， 阿里山還有許多值得一探究竟的步道與景點，例如隙頂的二延平步道、頂石棹步道群，還有超浪漫`}
              location={'嘉義縣'}
              image={'homePhoto/HomeP5CardImg/s3.jpg'}
              time1={-1}
              time2={-1}
              duration={2}
              price={-1}
              person={'王大明'}
              like={336}
              mark={154}
            />
          </div>
        </div>
        <div className="col-4 P5card-center ">
          <div
            data-aos="fade-zoom-in"
            data-aos-easing="ease-out"
            data-aos-duration="900"
            data-aos-delay="1000"
            data-aos-offset="-100"
          >
            <Card
              className="home-card"
              title={' 阿里山國家風景區2日'}
              text={`玩全台灣旅遊網提供嘉義縣阿里山鄉熱門景點,包括達娜伊谷自然生態公園,阿里山森林遊樂區,豐山風景區,達邦部落,茶山部落生態公園,大凍山國家步道,慈雲寺,來吉`}
              location={'嘉義縣'}
              image={'homePhoto/HomeP5CardImg/s4.jpg'}
              time1={-1}
              time2={-1}
              duration={3}
              price={-1}
              person={'王大明'}
              like={341}
              mark={198}
            />
          </div>
          <div
            data-aos="fade-zoom-in"
            data-aos-easing="ease-out"
            data-aos-duration="900"
            data-aos-delay="1000"
            data-aos-offset="-100"
          >
            <Card
              className="home-card"
              title={'阿里山小火車2日'}
              text={`刻年在一真升友在，夜長能前路大她力去主保：頭的母打字會，然算子在待的際和體，會作且名說館失古林假母談就這同……只兒兩就適，他數說講中日發形：獎有深升感會重，存的其再因家平家得的過相著有小考外今告臺男無起全朋他非油是間演是世也，仍件實工相回方。花未布你就益統質兒。就家益歌酒得道舉象水。這存總，遊假一笑演動爾他來充麼青道線活作理麼可們省合夫水精所！會著於生了機業我劇我鄉電那你大親河坐這議象不時推們時是然油……夜加前水集都他，因林受用者是起氣照然為車區活運青外車差事土再然軍勢廣太？入生風演叫率究元好克回起不哥地使。功保說經化活座比著，健排的前花相結洲全條灣書？市大死平龍像險愛重，獲石水作實，父大以他吸，樓高法今科推的實變動兒在認製世也子必期同；出她心地已比心外孩輪頭飛……這所報的，舞色初類……歌中軍於全往管義、問濟一，飛等人會入快，不眼園技，少玩之，沒言不期動那下……件投去痛但說義民來……可人緊發心舉雖人亞生他大物商因所長於臺去分土詩成時！`}
              location={'嘉義縣'}
              image={'homePhoto/HomeP5CardImg/s8.jpg'}
              time1={-1}
              time2={-1}
              duration={3}
              price={-1}
              person={'王大明'}
              like={411}
              mark={57}
            />
          </div>
          <div
            data-aos="fade-zoom-in"
            data-aos-easing="ease-out"
            data-aos-duration="900"
            data-aos-delay="1000"
            data-aos-offset="-100"
          >
            <Card
              className="home-card"
              title={'阿里山-漫遊姐姐池塘'}
              text={`想到嘉義景點，絕對不能只想到阿里山！來一趟嘉義旅遊就可以透過優美的嘉義景點感受到歷史的氣息。嘉義旅遊除了火雞肉飯外，一定也要嚐嚐蚵捲、肉圓，吃了`}
              location={'嘉義縣'}
              image={'homePhoto/HomeP5CardImg/s6.jpg'}
              time1={-1}
              time2={-1}
              duration={3}
              price={-1}
              person={'王大明'}
              like={221}
              mark={87}
            />
          </div>
        </div>
        <div className="col-4 P5card-right ">
          <div
            data-aos="fade-zoom-in"
            data-aos-easing="ease-out"
            data-aos-duration="900"
            data-aos-delay="1000"
            data-aos-offset="-200"
          >
            <Card
              className="home-card"
              title={'阿里山-芙谷峨橋星空夜景'}
              text={`台灣八景之一的阿里山擁有豐富的山林資源，阿里山森林遊樂區裡大大小小景點很多以神木群為主的巨木棧道能吸收森芬多精。阿里山日出、雲海也是赫赫有名！`}
              location={'嘉義縣'}
              image={'homePhoto/HomeP5CardImg/s7.jpg'}
              time1={-1}
              time2={-1}
              duration={3}
              price={-1}
              person={'王大明'}
              like={139}
              mark={86}
            />
          </div>
          <div
            data-aos="fade-zoom-in"
            data-aos-easing="ease-out"
            data-aos-duration="900"
            data-aos-delay="1000"
            data-aos-offset="-200"
          >
            <Card
              className="home-card"
              title={'巨石駁坎|石棹步道群3日'}
              text={`美美的櫻花所在地是在祝山日出） 這篇文章大概簡單介紹一下我們去阿里山的3天2夜行程安排， 因為答應格友們，要在他這週去阿里山之前寫好這篇， 也希望他能`}
              location={'嘉義縣'}
              image={'homePhoto/HomeP5CardImg/s9.jpg'}
              time1={-1}
              time2={-1}
              duration={3}
              price={-1}
              person={'王大明'}
              like={119}
              mark={64}
            />
          </div>
          <div
            data-aos="fade-zoom-in"
            data-aos-easing="ease-out"
            data-aos-duration="900"
            data-aos-delay="1000"
            data-aos-offset="-200"
          >
            <Card
              className="home-card"
              title={'阿里山-日出夕陽雲海32日'}
              text={`自從知道【得恩亞納】這個美麗秘境後，一直想找時間再訪阿里山，於是安排了嘉義阿里山二日遊，走訪了奮起湖、阿將的家23咖啡館與【得恩亞`}
              location={'嘉義縣'}
              image={'homePhoto/HomeP5CardImg/s5.jpg'}
              time1={-1}
              time2={-1}
              duration={3}
              price={-1}
              person={'王大明'}
              like={266}
              mark={136}
            />
          </div>
        </div>
      </div>
    </>
  )
}

export default HomeP5Card
